package com.shusheng.tihuzhai.dao.entity.auto;

import java.io.Serializable;
import java.util.Date;

public class AcRoleMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_role_menu.id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_role_menu.role_id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_role_menu.menu_id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    private Long menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_role_menu.status
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_role_menu.row_add_time
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_role_menu
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_role_menu.id
     *
     * @return the value of ac_role_menu.id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_role_menu.id
     *
     * @param id the value for ac_role_menu.id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_role_menu.role_id
     *
     * @return the value of ac_role_menu.role_id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_role_menu.role_id
     *
     * @param roleId the value for ac_role_menu.role_id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_role_menu.menu_id
     *
     * @return the value of ac_role_menu.menu_id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public Long getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_role_menu.menu_id
     *
     * @param menuId the value for ac_role_menu.menu_id
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_role_menu.status
     *
     * @return the value of ac_role_menu.status
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_role_menu.status
     *
     * @param status the value for ac_role_menu.status
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_role_menu.row_add_time
     *
     * @return the value of ac_role_menu.row_add_time
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_role_menu.row_add_time
     *
     * @param rowAddTime the value for ac_role_menu.row_add_time
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role_menu
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleId=").append(roleId);
        sb.append(", menuId=").append(menuId);
        sb.append(", status=").append(status);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}