spring:
  profiles:
    active: localhost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

mybatis:
  mapper-locations: classpath:automapperxmls/**/*.xml
  type-aliases-package: com.shusheng.tihuzhai.dao.autoentity

server:
  port: 8899

---
#spring:
spring:
  profiles: localhost
  datasource:
    url: jdbc:mysql://47.96.128.191:5600/born_hichina?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: c_hichina
    password: efH123K1dKh3sd

logging:
  file: D:/var/log/webapps/hichina.log

---
#spring:
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://47.96.128.191:5600/born_hichina?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: c_hichina
    password: efH123K1dKh3sd

---
#spring:
spring:
  profiles: online
  datasource:
    url: jdbc:mysql://47.96.128.191:5600/born_hichina?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
    username: c_hichina
    password: efH123K1dKh3sd

