spring:
  profiles:
    active: localhost
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 100
      max-wait: 60000
      time-between-eviction-runs-millis: 2000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid

server:
  port: 8899

mybatis:
  mapper-locations: classpath:mapperxml/pgsql/**/*.xml
  type-aliases-package: com.shusheng.tihuzhai.dao.pgsql.entity

---
#spring:
spring:
  profiles: localhost
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://47.106.102.151:5432/tihuboss?useSSL=false
    username: postgres
    password: postgres

logging:
  file: D:/var/log/webapps/tihuzhai.log

---
##spring:
#spring:
#  profiles: test
#  datasource:
#    url: jdbc:mysql://47.106.102.151:3306/tihuzhai?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
#    username: root
#    password: aaaa1111
#
#---
##spring:
#spring:
#  profiles: online
#  datasource:
#    url: jdbc:mysql://47.106.102.151:3306/tihuzhai?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
#    username: root
#    password: aaaa1111

