package com.shusheng.tihuzhai.dao.pgsql.mappers.auto;

import com.shusheng.tihuzhai.dao.pgsql.entity.auto.AcUserRole;
import com.shusheng.tihuzhai.dao.pgsql.entity.auto.AcUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AcUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int countByExample(AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int deleteByExample(AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int insert(AcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int insertSelective(AcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    List<AcUserRole> selectByExampleWithRowbounds(AcUserRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    List<AcUserRole> selectByExample(AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    AcUserRole selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") AcUserRole record, @Param("example") AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int updateByExample(@Param("record") AcUserRole record, @Param("example") AcUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int updateByPrimaryKeySelective(AcUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    int updateByPrimaryKey(AcUserRole record);
}