package com.shusheng.tihuzhai.dao.pgsql.entity.auto;

import java.io.Serializable;
import java.util.Date;

public class AcMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.parent_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.menu_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String menuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.menu_code
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String menuCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.menu_type
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String menuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.menu_order
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Integer menuOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.permission_url
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String permissionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.menu_status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String menuStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.memo
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_menu.row_update_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Date rowUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_menu
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.id
     *
     * @return the value of ac_menu.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.id
     *
     * @param id the value for ac_menu.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.parent_id
     *
     * @return the value of ac_menu.parent_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.parent_id
     *
     * @param parentId the value for ac_menu.parent_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.menu_name
     *
     * @return the value of ac_menu.menu_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMenuName() {
        return menuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.menu_name
     *
     * @param menuName the value for ac_menu.menu_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMenuName(String menuName) {
        this.menuName = menuName == null ? null : menuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.menu_code
     *
     * @return the value of ac_menu.menu_code
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMenuCode() {
        return menuCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.menu_code
     *
     * @param menuCode the value for ac_menu.menu_code
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMenuCode(String menuCode) {
        this.menuCode = menuCode == null ? null : menuCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.menu_type
     *
     * @return the value of ac_menu.menu_type
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMenuType() {
        return menuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.menu_type
     *
     * @param menuType the value for ac_menu.menu_type
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMenuType(String menuType) {
        this.menuType = menuType == null ? null : menuType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.menu_order
     *
     * @return the value of ac_menu.menu_order
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Integer getMenuOrder() {
        return menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.menu_order
     *
     * @param menuOrder the value for ac_menu.menu_order
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMenuOrder(Integer menuOrder) {
        this.menuOrder = menuOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.permission_url
     *
     * @return the value of ac_menu.permission_url
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getPermissionUrl() {
        return permissionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.permission_url
     *
     * @param permissionUrl the value for ac_menu.permission_url
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setPermissionUrl(String permissionUrl) {
        this.permissionUrl = permissionUrl == null ? null : permissionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.menu_status
     *
     * @return the value of ac_menu.menu_status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMenuStatus() {
        return menuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.menu_status
     *
     * @param menuStatus the value for ac_menu.menu_status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMenuStatus(String menuStatus) {
        this.menuStatus = menuStatus == null ? null : menuStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.memo
     *
     * @return the value of ac_menu.memo
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.memo
     *
     * @param memo the value for ac_menu.memo
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.row_add_time
     *
     * @return the value of ac_menu.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.row_add_time
     *
     * @param rowAddTime the value for ac_menu.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_menu.row_update_time
     *
     * @return the value of ac_menu.row_update_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_menu.row_update_time
     *
     * @param rowUpdateTime the value for ac_menu.row_update_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_menu
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", menuName=").append(menuName);
        sb.append(", menuCode=").append(menuCode);
        sb.append(", menuType=").append(menuType);
        sb.append(", menuOrder=").append(menuOrder);
        sb.append(", permissionUrl=").append(permissionUrl);
        sb.append(", menuStatus=").append(menuStatus);
        sb.append(", memo=").append(memo);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", rowUpdateTime=").append(rowUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}