package com.shusheng.tihuzhai.dao.pgsql.entity.auto;

import java.io.Serializable;
import java.util.Date;

public class AcUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_role.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_role.user_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_role.role_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_role.status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user_role.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_role.id
     *
     * @return the value of ac_user_role.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_role.id
     *
     * @param id the value for ac_user_role.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_role.user_id
     *
     * @return the value of ac_user_role.user_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_role.user_id
     *
     * @param userId the value for ac_user_role.user_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_role.role_id
     *
     * @return the value of ac_user_role.role_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_role.role_id
     *
     * @param roleId the value for ac_user_role.role_id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_role.status
     *
     * @return the value of ac_user_role.status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_role.status
     *
     * @param status the value for ac_user_role.status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user_role.row_add_time
     *
     * @return the value of ac_user_role.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user_role.row_add_time
     *
     * @param rowAddTime the value for ac_user_role.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user_role
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", status=").append(status);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}