package com.shusheng.tihuzhai.dao.pgsql.entity.auto;

import java.io.Serializable;
import java.util.Date;

public class AcUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.user_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.user_real_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String userRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.password
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.email
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.mobile
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.password_error_times
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Integer passwordErrorTimes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.user_status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String userStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.memo
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private String memo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Date rowAddTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ac_user.row_update_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private Date rowUpdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ac_user
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.id
     *
     * @return the value of ac_user.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.id
     *
     * @param id the value for ac_user.id
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.user_name
     *
     * @return the value of ac_user.user_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.user_name
     *
     * @param userName the value for ac_user.user_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.user_real_name
     *
     * @return the value of ac_user.user_real_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getUserRealName() {
        return userRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.user_real_name
     *
     * @param userRealName the value for ac_user.user_real_name
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setUserRealName(String userRealName) {
        this.userRealName = userRealName == null ? null : userRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.password
     *
     * @return the value of ac_user.password
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.password
     *
     * @param password the value for ac_user.password
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.email
     *
     * @return the value of ac_user.email
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.email
     *
     * @param email the value for ac_user.email
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.mobile
     *
     * @return the value of ac_user.mobile
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.mobile
     *
     * @param mobile the value for ac_user.mobile
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.password_error_times
     *
     * @return the value of ac_user.password_error_times
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Integer getPasswordErrorTimes() {
        return passwordErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.password_error_times
     *
     * @param passwordErrorTimes the value for ac_user.password_error_times
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setPasswordErrorTimes(Integer passwordErrorTimes) {
        this.passwordErrorTimes = passwordErrorTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.user_status
     *
     * @return the value of ac_user.user_status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getUserStatus() {
        return userStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.user_status
     *
     * @param userStatus the value for ac_user.user_status
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setUserStatus(String userStatus) {
        this.userStatus = userStatus == null ? null : userStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.memo
     *
     * @return the value of ac_user.memo
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public String getMemo() {
        return memo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.memo
     *
     * @param memo the value for ac_user.memo
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setMemo(String memo) {
        this.memo = memo == null ? null : memo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.row_add_time
     *
     * @return the value of ac_user.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Date getRowAddTime() {
        return rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.row_add_time
     *
     * @param rowAddTime the value for ac_user.row_add_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setRowAddTime(Date rowAddTime) {
        this.rowAddTime = rowAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ac_user.row_update_time
     *
     * @return the value of ac_user.row_update_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public Date getRowUpdateTime() {
        return rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ac_user.row_update_time
     *
     * @param rowUpdateTime the value for ac_user.row_update_time
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    public void setRowUpdateTime(Date rowUpdateTime) {
        this.rowUpdateTime = rowUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_user
     *
     * @mbggenerated Tue Sep 17 10:18:39 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userName=").append(userName);
        sb.append(", userRealName=").append(userRealName);
        sb.append(", password=").append(password);
        sb.append(", email=").append(email);
        sb.append(", mobile=").append(mobile);
        sb.append(", passwordErrorTimes=").append(passwordErrorTimes);
        sb.append(", userStatus=").append(userStatus);
        sb.append(", memo=").append(memo);
        sb.append(", rowAddTime=").append(rowAddTime);
        sb.append(", rowUpdateTime=").append(rowUpdateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}