package com.shusheng.tihuzhai.dao.mappers.auto;

import com.shusheng.tihuzhai.dao.entity.auto.AcRole;
import com.shusheng.tihuzhai.dao.entity.auto.AcRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface AcRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int countByExample(AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int deleteByExample(AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int insert(AcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int insertSelective(AcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    List<AcRole> selectByExampleWithRowbounds(AcRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    List<AcRole> selectByExample(AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    AcRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") AcRole record, @Param("example") AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int updateByExample(@Param("record") AcRole record, @Param("example") AcRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int updateByPrimaryKeySelective(AcRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ac_role
     *
     * @mbggenerated Mon May 13 14:12:13 CST 2019
     */
    int updateByPrimaryKey(AcRole record);
}